# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cabana' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cabana
  
  # add the Firebase pods
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  # pod 'Firebase/Storage'
  # pod 'Firebase/Database'
  # pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  
  # pod 'FirebaseUI/Auth'
  # pod 'FirebaseUI/Phone'
  
  pod 'FacebookLogin'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  
  target 'cabanaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cabanaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
